#!/usr/bin/env bash

ROOT="$( cd "$(dirname "$0")/.." ; pwd -P )"

cd "$ROOT/test"

THEME="suka"
THEME_DIRS=("static" "templates")

# hard reset
rm -rf $ROOT/test/themes/$THEME
mkdir $ROOT/test/themes/$THEME

for DIR in ${THEME_DIRS[@]}; do
  cp -R "$ROOT/$DIR" "$ROOT/test/themes/$THEME"
done

veripress preview --debug